# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: "0 23 * * 0"
  displayName: "Weekly Sunday build"
  branches:
    include:
    - master
  always: "true"
  
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'gallows/chuck'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: Docker@2
      displayName: Login
      inputs:
        containerRegistry: 'dockerhub'
        command: 'login'
    
    - task: Docker@2
      displayName: Build the Docker image
      inputs:
        repository: '$(imageName)'
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest

    - task: CmdLine@2
      displayName: Scan
      inputs:
        script: |
          docker run -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/mnt --rm aquasec/trivy --format template --template "@contrib/junit.tpl" --output /mnt/report.xml -q gallows/chuck
          cp $PWD/report.xml $(Build.ArtifactStagingDirectory)/report.xml

    - task: Docker@2
      displayName: "Push to Dockerhub"
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'gallows/chuck'
        command: 'push'
        tags: '$(tag)'
  
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: $(Build.ArtifactStagingDirectory)/report.xml
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'Trivy'
      condition: 'always()'