---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-demo
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
    name: flask-demo
    namespace: flask-demo
    labels:
        k8s-app: flask-demo
spec:
    replicas: 1
    selector:
        matchLabels:
            k8s-app: flask-demo
    template:
        metadata:
            name: flask-demo
            labels:
                k8s-app: flask-demo
        spec:
            containers:
                - 
                    name: flask-demo
                    image: 'gallows/chuck:latest'
                    resources:
                        requests:
                            memory: 256Mi
                    imagePullPolicy: Always
                    securityContext:
                        privileged: false
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
            securityContext: {}
            schedulerName: default-scheduler
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: '25%'
            maxSurge: '25%'
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
    name: flask-demo
    namespace: flask-demo
    labels:
        k8s-app: flask-demo
spec:
    ports:
        - 
            name: tcp-80-5000-zhmm5
            protocol: TCP
            port: 80
            targetPort: 5000
            nodePort: 32588
    selector:
        k8s-app: flask-demo
    type: LoadBalancer
    sessionAffinity: None
    externalTrafficPolicy: Cluster
